### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kirk86** [albbus-stack/upscale-io#2]
I was trying to see how reliably this works but I was met with the following error
![image](https://user-images.githubusercontent.com/2902390/148970120-a2a8a415-bcba-4acb-b2ad-a066e48a52e4.png)

**Comment by albbus-stack** [comment]
First of all thank you for your interest, this is a known issue because I host this on a free heroku worker that doesn't have enough memory to complete the task. If you still want to check out how this works just build it yourself locally following the instructions in the readme.

**Comment by albbus-stack** [comment]
I made this clear in the readme with PR #3
